# TMDb API Configuration
tmdb.api.key=931c36d3c86fab668959fdecb8ac6618

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

server.error.whitelabel.enabled=true
spring.thymeleaf.cache=false  
# Optional, to disable template caching during development

server.port=8080


